from __future__ import annotations

SCREEN_WIDTH = 256
SCREEN_HEIGHT = 192
WINDOW_TITLE = "DriftWithMe"
FPS = 30

BACKGROUND_COLOR = 1
ROAD_COLOR = 5
ROAD_LINE_COLOR = 13
TEXT_COLOR = 7
ACCENT_COLOR = 10
PLAYER_COLOR = 11
SHADOW_COLOR = 0
